project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "EEGManySteps"
  site-url: https://eegmanysteps.org
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: news.qmd
        text: News
      - href: team.qmd
        text: Team
      - href: datasets.qmd
        text: Datasets
      - href: join.qmd
        text: Join

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    grid:
      sidebar-width: 40px
