---
title: "EEGManySteps - Team"
---

This page serves an an overview of individuals who have agreed to support to the **EEGManySteps** project.
The definition of roles and responsibilities can be found at the bottom of this page.

## (current) Steering Committee Members (with affiliation)
- Melanie Klapprott (Oldenburg University, Germany)
- Liyu Cao (Zhejiang University, China)
- Aitana Grasso Cladera (Osnabrück University, Germany)
- Sein Jeung (TU Berlin, Germany)
- Simon Ladouce (KU Leuven, Belgium)
- Janna Protzak (Emory University, USA)
- Julian Reiser (IfADO, Germany)
- Seyed Yahya Shirazi (SCCN, USA)
- Julius Welzel (Kiel University, Germany)
- Anna Wunderlich (TU Berlin, Germany)
- Sodiq Fakorede (Kansas Medical Center, USA)
- Martin Geiger (Stuttgart University, Germany)
- Joris van der Cruijsen (Radboud University, Netherlands)
- Daniel Büchel (German Sports University Köln, Germany)
- Zurna Ahmed (University of Goettingen, Germany)
- Pema Sherpa (TU Berlin, Germany)
- Aime Aguilar-Herrera (University of Houston, USA)
- Denis Barbusse (Université Bourgogne, France)

## (current) Advisory Board Members (with affiliation)
- Fiorenzo Artoni (University of Geneva, Switzerland)
- Tjeerd Boonstra (Maastricht University, Netherlands)
- Stefan Debener (Oldenburg University, Germany)
- Benedikt Ehinger (Stuttgart University, Germany)
- Dan Ferris (University of Florida, USA)
- Hannes Devos (University of Kansas Medical Center)
- Klaus Gramann (TU Berlin, Germany)
- Barbara Händel (Würzburg University, Germany)
- Julia Kline (National Institutes of Health, USA)
- John Iversen (SCCN, USA)
- Agatha Lenartowicz (UCLA, USA)
- Scott Makeig (SCCN, USA)
- Walter Maetzler (Kiel University, Germany)
- Uroš Marušič (Science and Research Centre Koper, Slovenia)
- Pierfilippo De Sanctis (Albert Einstein College of Medicine, USA)
- Mathias Vukelic (Universität Stuttgart/Fraunhofer IAO, Germany)
- Edmund Wascher (IfADO, Germany)
- Bernadette van Wijk (Vrije Universiteit Amsterdam, Netherlands)
- Bettina Wollesen (German Sport University Cologne, Germany)
- Tomer Yona (Israel Institute of Technology, Israel)
- Catharina Zich (University College London, UK)
- Natalie Richter (University of Winnipeg, USA)
- Claudia Gianelli (Università di Messina, Italy)
- Alan Evans (McGill University, Canada)
- Christine Rogers (McGill University, Canada)
- Pedro Antonio Valdes-Sosa (University of Electronic Science and Technology of China)
- Pepe Contreras-vidal (University of Houston, USA)

## Role Definitions

### Steering Committee 
Expected to attend monthly meetings and take on specific tasks within the project.
*Minimal requirement: Authorship in one or more peer-reviewed MoBI paper or extensive experience in similar open science projects. Minimum active period at least 1 year.*

### Advisory Board 
Provide background support and feedback during quarterly/biannual meetings to guide the project’s direction.
*Minimal requirement: First or last author in a peer-reviewed MoBI/Biomechanics paper or extensive experience in similar open science projects. Minimum active period at least 1 year.*


Some additional roles will become relevant later in the project:

**[Data Set Contributors]**
Provide access to EEG datasets recorded in mobile settings. Detailed requirements are still to be determined.
Minimal requirement: Responsible for the acquisition, curation, or formatting of mobile EEG data.

**[Analysts]**
Participate in analyzing specific research questions related to mobile EEG data.
Minimal requirement: Experience with the analysis of biomechanical or MoBI data.

## Past contributors 
Nadine Jacobsen (SC, Oldenburg University, Germany)
Yu-Fang Yang (SC, FU Berlin, Germany)
Xinyu Chen (SC, Zhejiang University, China)
Elena Cesnaite (SC, Münster University, Germany)
